version: "3"

networks:
    eshopstore-net:
        driver: bridge

services: 
    
    ese-rabbitmq:
        image: rabbitmq:3-management
        container_name: eshopstore-rabbitmq
        hostname: eshopstore-rabbitmq
        networks:
            - eshopstore-net
        ports:
        - "15672:15672"
        - "25672:25672"
        - "5671:5671"
        - "5672:5672"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "eshop"
            RABBITMQ_DEFAULT_PASS: "eshop"
            RABBITMQ_DEFAULT_VHOST: "/"
        
    ese-sqlserver:
        image: avs/eshopstore-db:latest
        container_name: eshopstore-sqlserver
        hostname: eshopstore-sqlserver
        networks:
            - eshopstore-net
        build: 
            context: ../docker
            dockerfile: ./sql/Dockerfile
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"              
            
    ese-api-catalog:
        image: avs/eshopstore-api-catalog:latest
        container_name: eshopstore-api-catalog
        hostname: eshopstore-api-catalog
        networks:
            - eshopstore-net
        build: 
            context: ../src
            dockerfile: ./Services/Catalog/ESE.Catalog.API/Dockerfile  
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5301;http://+5302 
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/eshopstore-certificate.pfx
        volumes:
            - ./certs:/https:ro           
        depends_on:
            - ese-rabbitmq
            - ese-db
    
    ese-web-mvc:
        image: avs/eshopstore-web-mvc:latest
        container_name: eshopstore-web-mvc
        hostname: eshopstore-web-mvc        
        build:
            context: ../src
            dockerfile: ./Presentation/Web/MVC/ESE.Store.MVC/Dockerfile
        restart: always            
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5001
        volumes: 
            - dpkeys:/var/data_protection_keys:rw      
        depends_on:
            - ese-api-catalog

    ese-nginx:
        image: avs/eshopstore-nginx:latest
        container_name: eshopstore-nginx
        hostname: eshopstore-nginx     
        build: 
            context: ../docker
            dockerfile: ./nginx/Dockerfile 
        restart: always 
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - ese-web-mvc    
volumes:
    dpkeys:            